# Project metadata
[project]
name = "AllThings3D Core Engine"
uri = "https://allthings3d.co.za"

[openscad]
version = "2026.01.19"
font-source = "auto"

[[model]]
file = "models/keychain.scad"
index = false
